- name: Demo on variables
  hosts: all
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.google.com