- name: Template Demo
  hosts: localhost
  connection: local
  vars:
    fruit_name:
      - pineapple
      - keer
      - sweet
  tasks:
    - name: Demo on template
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt