- name: Template Demo
  hosts: localhost
  connection: local
  vars:
    fruit_name:
      - apple
      - orange
      - banana
  tasks:
    - name: Demo on template
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt