- name: demo on template
  hosts: localhost
  connection: local
  vars:
    fruit_name: banana
  tasks:
    - name: Demo on Template
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt