- name: Demo on Template
  hosts: localhost
  connection: local
  vars:
    Employee_id: 2223342
  tasks:
    - name: Print Employee ID
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt